av_node_right:
  ros__parameters:

    camera_name: DEV_1AB22C00BBE6

    publishers:
      raw_frame: /camera_right/raw_frame

    services:
      stop_camera: /camera_right/get_cam_state

    frames: 
      camera_link: camera_right_link
      
    rotation_angle: 0.0
    
    resize_image: True
    resized_width: 808
    resized_height: 608

    auto_exposure: Once
