stereo_calibration:
  ros__parameters:

    number_of_images_to_calibrate: 50
    minimum_valid_images: 5

    board_dim: [5, 7]
    square_size: 22.0 # mm

    width_image: 1000
    height_image: 1000

    subscribers:
      camera_left: /camera_left/raw_frame
      camera_right: /camera_right/raw_frame

    auto_capture:
      mode: True            # Capture an image every
      time_for_frame: 2.0   # sec

    single_cameras_calibrated: False
    
    calibration_path: /home/marco/xarm_devel/src/ROS2-Stereo-3D-Reconstruction/calibration/
