calibration_node:
  ros__parameters:

    subscribers:
      camera: /camera/raw_frame

    auto_capture:
      mode: True            # Capture an image every
      time_for_frame: 2.0   # sec
    
    # calibration_path: auto  # Specify absolute path instead
    calibration_path: /home/antonino/Desktop/work/stereo_ws/src/ROS2-Stereo-3D-Reconstruction/calibration/
