stereo_calibration:
  ros__parameters:

    number_of_images_to_save: 20
    minimum_valid_images: 5

    board_dim: [5, 7]
    square_size: 22.0 # mm

    width_image: 808
    height_image: 608

    subscribers:
      camera_left: /camera_left/raw_frame
      camera_right: /camera_right/raw_frame

    auto_capture:
      mode: True            # Capture an image every
      time_for_frame: 2.0   # sec

    single_cameras_calibrated: False
    
    images_path: /home/antonino/Desktop/work/stereo_ws/src/ROS2-Stereo-Reconstruction/calibration_images
